### ISSUE TITLE
hunk failed

### ISSUE THREAD

**Issue by exekutive** [justinmayer/homebrew-tap#10]
==> Installing justinmayer/tap/ffmpeg --HEAD --with-chromaprint --with-fdk-aac --with-game-music-emu --with-librsvg --with-libsoxr --with-li
==> Patching
==> Applying 7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315.patch
patching file libavformat/libsrt.c
Hunk #1 FAILED at 313.
Hunk #2 FAILED at 337.
2 out of 2 hunks FAILED -- saving rejects to file libavformat/libsrt.c.rej

**Comment by justinmayer** [comment]
Do you see the same result if you add `--with-srt` ?

**Comment by exekutive** [comment]
these were my options:
```
brew install justinmayer/tap/ffmpeg \
--with-chromaprint \
--with-fdk-aac \
--with-game-music-emu \
--with-libbluray \
--with-libbs2b \
--with-libcaca \
--with-libgsm \
--with-libmodplug \
--with-librsvg \
--with-libsoxr \
--with-libssh \
--with-libvidstab \
--with-libvmaf \
--with-opencore-amr \
--with-openh264 \
--with-openjpeg \
--with-openssl \
--with-rtmpdump \
--with-rubberband \
--with-speex \
--with-srt \
--with-tesseract \
--with-two-lame \
--with-wavpack \
--with-webp \
--with-xvid \
--with-zeromq \
--with-zimg \
--HEAD
```

**Comment by justinmayer** [comment]
I don't see any problems when using `--with-chromaprint --with-fdk-aac --with-srt` options, so I suspect this is related to one or more of the options selected. Perhaps try removing `--with-game-music-emu`, which is a new addition. Does that resolve the issue?

**Comment by exekutive** [comment]
I ended up using the "homebrew-ffmpeg" fork. Had the same issue there. Resolved it by removing '--with-game-music-emu' and '-HEAD' options.

https://github.com/homebrew-ffmpeg/homebrew-ffmpeg/issues/58

**Comment by justinmayer** [comment]
Thanks for the update. I imagine this will be resolved in the next FFmpeg release.
