### ISSUE TITLE
Invalid options

### ISSUE THREAD

**Issue by talha131** [justinmayer/homebrew-tap#2]
Related to #1 

Following options used to work with brew ffmpeg. Using them with this tag gave `invalid option error`.

1. with-sdl2 
1. with-snappy 
1. with-tools 
1. with-x265 
1. with-xz 
1. with-fontconfig 
1. with-freetype

I am not sure if it's a tap issue or ffmpeg has dropped these options.

**Comment by justinmayer** [comment]
Hey Talha. This is likely a documentation issue more than anything else; I simply haven't found the time to put together more detailed information in the README, but hopefully that will change in the not-too-distant future.

Short version: I don't think you don't need to specify any of those options. All but one of the above have been moved from options to [dependencies](https://github.com/justinmayer/homebrew-tap/blob/master/Formula/ffmpeg.rb#L37-L51), so specifying them is redundant. The only exception among the items you listed is `with-tools` — I don't know what that option did previously, but I get the feeling that now it is [also redundant](https://github.com/justinmayer/homebrew-tap/blob/master/Formula/ffmpeg.rb#L169-L172).

**Comment by talha131** [comment]
Thank you @justinmayer.
