### ISSUE TITLE
Encounter 'invalid option'

### ISSUE THREAD

**Issue by windtalkerlv** [justinmayer/homebrew-tap#3]
Trying to install with command `brew install justinmayer/tap/ffmpeg --with-chromaprint` met with error `Error: invalid option: --with-chromaprint`
I tried with `--with-fdk-aac` and encountered similar error. I read the closed issues and checked `ffmpeg.rb` and none of them are dependencies.

**Comment by justinmayer** [comment]
I'm sorry to hear that you ran into a problem, Maxim. I can't reproduce it, unfortunately, so I'm going to close this issue for the time being.
