### ISSUE TITLE
Problems building FFMPEG on Catalina, workaround available.

### ISSUE THREAD

**Issue by AstroDan** [justinmayer/homebrew-tap#5]
Looks like some defaults changed in the compiler.  See https://trac.ffmpeg.org/ticket/8073

Incorporation of their fix seems simple:

From line 87 of ffmpeg.rb

 ```
def install
    # Work around Xcode 11 clang bug
    # https://bitbucket.org/multicoreware/x265/issues/514/wrong-code-generated-on-macos-1015
    ENV.append_to_cflags "-fno-stack-check" if DevelopmentTools.clang_build_version >= 1010
    args = %W[
```

**Comment by justinmayer** [comment]
@AstroDan: Thanks for the heads-up. My personal assessment is that Catalina currently offers a low benefit-to-cost ratio, so I don't intend on upgrading to it any time soon. If someone can test that this formula change compiles correctly and works well on 10.13 – 10.15, by all means please submit a pull request. That would be helpful and much appreciated. 😁

**Comment by justinmayer** [comment]
I don't believe this is an issue any longer. Feel free to comment if you believe otherwise.
