### ISSUE TITLE
failed, MacOS 10.13.6 High Sierra

### ISSUE THREAD

**Issue by rowe-morehouse** [justinmayer/homebrew-tap#8]
==> ./configure --prefix=/usr/local/Cellar/ffmpeg/4.2.3 --enable-shared --cc=c
Last 15 lines from /Users/dickhertz/Library/Logs/Homebrew/ffmpeg/01.configure:
--enable-nonfree
--enable-decklink
--extra-cflags=-I/usr/local/include
--extra-ldflags=-L/usr/local/include
--enable-version3
--enable-libopencore-amrnb
--enable-libopencore-amrwb

ERROR: DeckLinkAPI.h not found

**Comment by rowe-morehouse** [comment]
Sorry, I realized this has nothing to do with your script. Sorry to bother you.

**Comment by justinmayer** [comment]
No worries. I've built this on High Sierra and didn't have any issues. Thank you for following up.
