### ISSUE TITLE
Can't build latest ffmpeg: "vf_blend.asm:416: out of memory"

### ISSUE THREAD

**Issue by JaceTBL** [justinmayer/homebrew-tap#9]
When trying to build the latest ffmpeg from this tap like so:
`brew install justinmayer/tap/ffmpeg`

I'm getting:

> .....
> X86ASM	libavfilter/x86/vf_blend.o
> CC	libavfilter/x86/vf_blend_init.o
> critical: libavfilter/x86/vf_blend.asm:416: out of memory!
> make: *** [libavfilter/x86/vf_blend.o] Error 2
> make: *** Waiting for unfinished jobs....

Actually I'm using the `--with-fdk-aac` option (that's why I use this tap) but the same error occurs without any options.

It used to work fine before (have been using this tap since 2019) but not anymore, no idea why. 

FYI I'm using macOS Catalina 10.15.5 (latest version) and already did `brew update`, `brew cleanup`, and `brew doctor`, all OK.

The 'out of memory' is unlikely, I have 32 GB ram, even rebooted my macbook and tried again without running any other applications or background stuff, still the same.

For what it's worth I also tried an another tap ([homebrew-ffmpeg](https://github.com/homebrew-ffmpeg/homebrew-ffmpeg)) which also offers the `--with-fdk-aac` option, exact same problem occurs there.

It does NOT occur when building the regular ffmpeg with homebrew: just `brew install ffmpeg` works fine. However that lacks the FDK AAC codec which I really need.

**Comment by justinmayer** [comment]
@JaceTBL / @vszakats: I don't see that problem, but I'm on Mojave and not Catalina. I just updated the FFmpeg tap to v4.3.1. Can you try again and see if you get the same results?

**Comment by vszakats** [comment]
@justinmayer This looks like an issue with a recent `nasm` update, and not something in `ffmpeg` itself. I could solve it by switching to use `yasm` (via `--x86asmexe=yasm`).

**Comment by justinmayer** [comment]
@vszakats: Yes, but above I suggested trying again because `nasm` was recently updated with a potential fix for this problem: https://github.com/Homebrew/homebrew-core/pull/57284

**Comment by vszakats** [comment]
Oh, right, I missed it. So, after reverting back to `nasm` (2.15.02), I can now confirm it _does_ build without any issues.
Thank you for your support!

**Comment by justinmayer** [comment]
Yay. Glad to hear it. 😁
